"use client";

import { useEffect, useState } from "react";
import { apiFetch, DEMO_DASHBOARD } from "../../lib/api";
import type { Dashboard } from "../../lib/types";
import { readUserId } from "../../lib/api";
import { AppShell } from "../../components/AppShell";

export default function AnalyticsPage() {
  const [dashboard, setDashboard] = useState<Dashboard>(DEMO_DASHBOARD);
  useEffect(() => { const userId = readUserId(); if (userId && userId !== "demo") apiFetch<Dashboard>(`/api/v1/dashboard?user_id=${encodeURIComponent(userId)}`).then(setDashboard).catch(() => undefined); }, []);
  return <AppShell><div className="flow-page"><header className="flow-header"><div><p className="eyebrow">Data / signal, not noise</p><h1>See the<br /><em>change.</em></h1></div><p>Calories are not the headline. This is the record of showing up, adapting, and getting stronger in more than one dimension.</p></header><div className="analytics-grid"><section className="analytics-panel"><p className="eyebrow">Consistency windows</p><h2>Keep the long view.</h2>{["7", "28", "90"].map((window) => { const value = dashboard.consistency[window] ?? { completed: 0, planned: Number(window), percentage: 0 }; return <div className="bar-row" key={window}><span>{window} days</span><div className="bar-track"><div className="bar-fill" style={{ width: `${value.percentage}%` }} /></div><strong className="bar-number">{Math.round(value.percentage)}%</strong></div>; })}</section><section className="analytics-panel"><p className="eyebrow">Execution</p><h2>Discipline is separate.</h2><div className="big-stat">{dashboard.discipline_level.split(" ")[0]}</div><p className="stat-caption">{dashboard.discipline_level} · {dashboard.xp.toLocaleString()} XP · {dashboard.total_training_minutes} training minutes</p></section><section className="analytics-panel"><p className="eyebrow">Fitness dimensions</p><h2>Different signals, one body.</h2>{Object.entries(dashboard.fitness_levels).map(([key, level]) => <div className="bar-row" key={key}><span>{key.replace("_", " ")}</span><div className="bar-track"><div className="bar-fill" style={{ width: `${Number(level.replace("F", "")) * 20}%`, background: key === "core" ? "var(--orange)" : "var(--blue)" }} /></div><strong className="bar-number">{level}</strong></div>)}</section><section className="analytics-panel"><p className="eyebrow">Next reassessment</p><h2>Compare, don&apos;t guess.</h2><div className="big-stat" style={{ color: "var(--blue)" }}>2–4<span style={{ fontSize: 22, letterSpacing: 0 }}> WKS</span></div><p className="stat-caption">A light reassessment updates the plan from actual performance, not from an AI guess.</p></section></div></div></AppShell>;
}
